### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by Faiyyazauxy** [Wes1324/eraser#1]
Hi,

Thank you for such a good library.

Can you please make it null safety compatible for flutter 2.0

**Comment by Wes1324** [comment]
Hey, no problem, I'm glad it has been useful to you. Yes, that is a good idea. I will look into it this weekend and attempt to make a new release on Sunday. Thanks

**Comment by Faiyyaz** [comment]
Hi, I had raised an issue for null safety version from my company account @Faiyyazauxy .

So here is a fork of mine with null safety version changes. Can you please check this once at your end and merge it & release a version.

Thanks

**Comment by Wes1324** [comment]
Hi,

Thank you very much for raising this issue and for creating a pull request. I have never migrated a package to null-safety and wanted to try it myself, so I created my own pull request and merged it this morning. A null-safe version of this package has now been released so I will close this issue.

Thanks again!
