### ISSUE TITLE
Badge not clearing AT ALL

### ISSUE THREAD

**Issue by kevinrobert3** [Wes1324/eraser#8]
I implemented this package and sent a notification and the badge was 1. I open the app and the badge is still there. I have cleared the app, switched off my phone, and uninstalled the app and back, nothing. I even went back to a previous version of the app where this package was not there and the badge still is present.
How is this even possible? Is this a bug in the package or iOS itself

**Comment by Wes1324** [comment]
What version of iOS are you testing on by the way?

**Comment by kevinrobert3** [comment]
this is iOS 16.6

**Comment by Wes1324** [comment]
The plugin currently uses `UNUserNotificationCenter.current().removeAllDeliveredNotifications()` to reset the badge count. This used to work when I wrote the plugin but doesn't work anymore.

`UIApplication.shared.applicationIconBadgeNumber = 0` does work for me locally but I'm not 100% sure what the difference is between these two.

I'll do some reading on the difference and then push a new version of the plugin once I've figured it out.

**Comment by Wes1324** [comment]
Hey, I appreciate it's taken me nearly 8 months to reply so you might not be interested in replying anymore but I've had a look into this and I'm struggling to see the issue.

I've just tested it using the example app included in the repo on an iPhone 11 running iOS 17.4.1 and it seems to be working fine (see attached video).

Can you confirm if this is still is an issue for you? If so, can you share a code snippet showing exactly how you are using the Eraser package to clear the badge count please.

Thanks

https://github.com/Wes1324/eraser/assets/25579138/50ea62a4-bbcf-41cf-9f1d-8ecc5bc77a9b

**Comment by Wes1324** [comment]
Closing this for now due to inactivity but feel free to open again if you see fit
